-- Mentor map: Database bootstrap script for the Crewmates project.
-- Why it exists: Creates schema and RLS policies so frontend CRUD works safely.
-- Mentor tip: Keep setup scripts idempotent so you can safely rerun in dev/test.
create table if not exists public."Crewmates" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  category text not null,
  color text not null,
  specialty text not null,
  speed integer not null check (speed between 1 and 5),
  stamina integer not null check (stamina between 1 and 5),
  bio text not null default ''
);

-- RLS should be explicit. Enable it before creating policies.
alter table public."Crewmates" enable row level security;

-- Policy: allow read access for anon/authenticated users.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can view crewmates'
  ) then
    create policy "Public can view crewmates"
      on public."Crewmates"
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

-- Week 9 final project: challenge posts table.
create table if not exists public."Posts" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  title text not null,
  description text not null,
  author_label text not null,
  author_id text not null,
  secret_key text not null,
  flag text not null default 'Question'
    check (flag in ('Question', 'Opinion', 'Showcase', 'Resource')),
  characteristic text not null default 'General',
  image_url text not null default '',
  video_url text not null default '',
  repost_of bigint references public."Posts" (id) on delete set null,
  "betCount" integer not null default 0 check ("betCount" >= 0)
);

-- If Posts already existed from an earlier version, backfill any missing columns.
alter table public."Posts" add column if not exists updated_at timestamptz not null default now();
alter table public."Posts" add column if not exists title text;
alter table public."Posts" add column if not exists description text;
alter table public."Posts" add column if not exists author_label text;
alter table public."Posts" add column if not exists author_id text;
alter table public."Posts" add column if not exists secret_key text;
alter table public."Posts" add column if not exists flag text not null default 'Question';
alter table public."Posts" add column if not exists characteristic text not null default 'General';
alter table public."Posts" add column if not exists image_url text not null default '';
alter table public."Posts" add column if not exists video_url text not null default '';
alter table public."Posts" add column if not exists repost_of bigint;
alter table public."Posts" add column if not exists "betCount" integer not null default 0;

-- Add FK only if it does not exist yet.
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'Posts_repost_of_fkey'
  ) then
    alter table public."Posts"
      add constraint "Posts_repost_of_fkey"
      foreign key (repost_of)
      references public."Posts" (id)
      on delete set null;
  end if;
end
$$;

-- Align defaults and required constraints for key fields in existing tables.
alter table public."Posts" alter column flag set default 'Question';
alter table public."Posts" alter column characteristic set default 'General';
alter table public."Posts" alter column image_url set default '';
alter table public."Posts" alter column video_url set default '';
alter table public."Posts" alter column "betCount" set default 0;

update public."Posts"
set
  title = coalesce(title, 'Untitled post'),
  description = coalesce(description, ''),
  author_label = coalesce(author_label, 'Pilot'),
  author_id = coalesce(author_id, 'legacy-user'),
  secret_key = coalesce(secret_key, 'legacy-key'),
  flag = coalesce(flag, 'Question'),
  characteristic = coalesce(characteristic, 'General'),
  image_url = coalesce(image_url, ''),
  video_url = coalesce(video_url, ''),
  "betCount" = coalesce("betCount", 0)
where
  title is null
  or description is null
  or author_label is null
  or author_id is null
  or secret_key is null
  or flag is null
  or characteristic is null
  or image_url is null
  or video_url is null
  or "betCount" is null;

alter table public."Posts" alter column title set not null;
alter table public."Posts" alter column description set not null;
alter table public."Posts" alter column author_label set not null;
alter table public."Posts" alter column author_id set not null;
alter table public."Posts" alter column secret_key set not null;
alter table public."Posts" alter column flag set not null;
alter table public."Posts" alter column characteristic set not null;
alter table public."Posts" alter column image_url set not null;
alter table public."Posts" alter column video_url set not null;
alter table public."Posts" alter column "betCount" set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'Posts_flag_check'
  ) then
    alter table public."Posts"
      add constraint "Posts_flag_check"
      check (flag in ('Question', 'Opinion', 'Showcase', 'Resource'));
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'Posts_betCount_check'
  ) then
    alter table public."Posts"
      add constraint "Posts_betCount_check"
      check ("betCount" >= 0);
  end if;
end
$$;

alter table public."Posts" enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Posts' and policyname = 'Public can view posts'
  ) then
    create policy "Public can view posts"
      on public."Posts"
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Posts' and policyname = 'Public can create posts'
  ) then
    create policy "Public can create posts"
      on public."Posts"
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Posts' and policyname = 'Public can update posts'
  ) then
    create policy "Public can update posts"
      on public."Posts"
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Posts' and policyname = 'Public can delete posts'
  ) then
    create policy "Public can delete posts"
      on public."Posts"
      for delete
      to anon, authenticated
      using (true);
  end if;
end
$$;

-- Week 9 final project: comments table for post threads.
create table if not exists public."Comments" (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  post_id bigint not null references public."Posts" (id) on delete cascade,
  content text not null,
  author_label text not null,
  author_id text not null
);

-- If Comments already existed from an earlier version, backfill missing columns.
alter table public."Comments" add column if not exists created_at timestamptz not null default now();
alter table public."Comments" add column if not exists post_id bigint;
alter table public."Comments" add column if not exists content text;
alter table public."Comments" add column if not exists author_label text;
alter table public."Comments" add column if not exists author_id text;

update public."Comments"
set
  content = coalesce(content, ''),
  author_label = coalesce(author_label, 'Pilot'),
  author_id = coalesce(author_id, 'legacy-user')
where
  content is null
  or author_label is null
  or author_id is null;

alter table public."Comments" alter column content set not null;
alter table public."Comments" alter column author_label set not null;
alter table public."Comments" alter column author_id set not null;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'Comments_post_id_fkey'
  ) then
    alter table public."Comments"
      add constraint "Comments_post_id_fkey"
      foreign key (post_id)
      references public."Posts" (id)
      on delete cascade;
  end if;
end
$$;

alter table public."Comments" enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Comments' and policyname = 'Public can view comments'
  ) then
    create policy "Public can view comments"
      on public."Comments"
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Comments' and policyname = 'Public can create comments'
  ) then
    create policy "Public can create comments"
      on public."Comments"
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'Comments' and policyname = 'Public can delete comments'
  ) then
    create policy "Public can delete comments"
      on public."Comments"
      for delete
      to anon, authenticated
      using (true);
  end if;
end
$$;

-- Storage bucket for uploaded post images.
insert into storage.buckets (id, name, public)
values ('post-media', 'post-media', true)
on conflict (id) do nothing;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can upload post-media objects'
  ) then
    create policy "Public can upload post-media objects"
      on storage.objects
      for insert
      to anon, authenticated
      with check (bucket_id = 'post-media');
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Public can read post-media objects'
  ) then
    create policy "Public can read post-media objects"
      on storage.objects
      for select
      to anon, authenticated
      using (bucket_id = 'post-media');
  end if;
end
$$;

-- Policy: allow insert access for anon/authenticated users.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can create crewmates'
  ) then
    create policy "Public can create crewmates"
      on public."Crewmates"
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

-- Policy: allow update access for anon/authenticated users.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can update crewmates'
  ) then
    create policy "Public can update crewmates"
      on public."Crewmates"
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

-- Policy: allow delete access for anon/authenticated users.
do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'Crewmates'
      and policyname = 'Public can delete crewmates'
  ) then
    create policy "Public can delete crewmates"
      on public."Crewmates"
      for delete
      to anon, authenticated
      using (true);
  end if;
end
$$;
